[package]
name = "ssb-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
polars = { version = "0.46.0", features = ["csv"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
rstest = "0.24.0"
